apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qq6
  name: realtime
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "500Mi"
            cpu: "0.5"
