apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: qq10
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort:
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
