apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: qq9
spec:
  containers:
  - name: alpine
    image: alpine:edge
    command:
    - "sh"
    - "-c"
    args:
    - while true; do echo 'HELLO ALPINE'; sleep 3; done