apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: http
  name: http
  namespace: qq8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http
    spec:
      containers:
      - image: traefik/whoami
        name: whoami
        ports:
        - containerPort: 80
        resources: {}
status: {}