apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: http
  name: http
  namespace: qq8
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: http
  type: LoadBalancer
status:
  loadBalancer: {}