apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: qq1
  name: nginx-daemonSet
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      tolerations:
      - key: "key1"
        operator: "Exists"
        effect: "NoSchedule"