apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: qq1
  labels:
    k8s-app: nginx
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      tolerations:
      - key: key1
        operator: Equal
        value: value1
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:latest