apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: examinee
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: examinee-binding
subjects:
- kind: User
  name: examinee
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: examinee
  apiGroup: rbac.authorization.k8s.io