apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      run: api-server
  template:
    metadata:
      labels:
        run: api-server
    spec:
      containers:
      - name: api-server
        image: nginx:1.18
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    run: api-server
spec:
  ports:
  - port: 80
  selector:
    run: api-server