apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: qq5
spec:
  selector:
    matchLabels:
      run: dashboard
  replicas: 1
  template:
    metadata:
      labels:
        run: dashboard
    spec:
      containers:
        - name: drupal
          image: drupal:10.2.7-php8.2-fpm-bookworm
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: qq5
  labels:
    run: dashboard
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: dashboard
