apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  labels:
    app: dashboard
  namespace: qq5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: drupal:10.2.7-php8.2-fpm-bookworm 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-dashboard
  namespace: qq5
spec:
  selector:
    app: dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dashboard
  namespace: qq5
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: dashboard.qq5.org
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-dashboard 
            port: