piVersion: apps/v1
kind: Deployment
metadata:
  namespace: qq5
  creationTimestamp: null
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal
    spec:
      containers:
      - image: drupal:10.2.7-php8.2-fpm-bookworm
        name: drupal
        resources: {}
status: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: qq5
spec:
  rules:
  - host: dashboard.qq5.org
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: dashboard
            port:
              number: 80