apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:latest
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password

       - name: mongo-express
         image: mongo-express:1.0.2-20-alpine3.19
         env:
          - name: ME_CONFIG_MONGODB_URL
            valueFrom:
              configMapKeyRef:
                  name: mongo-cm
                  key: ME_CONFIG_MONGODB_URL
          - name: ME_CONFIG_BASICAUTH
            valueFrom:
              configMapKeyRef:
                name: mongo-cm
                key: ME_CONFIG_BASICAUTH
          - name: MME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: user
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-cm
data:
  ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
  ME_CONFIG_BASICAUTH: "false"


---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  user: QWltYW4=
  password: YWJjMTIz