---
apiVersion: v1
kind: Namespace
metadata:
  name: qq3

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: qq3
data:
  ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
  ME_CONFIG_BASICAUTH: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: qq3
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example
  ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ME_CONFIG_MONGODB_ADMINPASSWORD: example

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: qq3
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mongo
        image: mongo
        envFrom:
        - secretRef:
            name: mongo-secret
        ports:
        - containerPort: 27017
      - name: mongo-express
        image: mongo-express
        envFrom:
        - configMapRef:
            name: mongo-express-config
        - secretRef:
            name: mongo-secret
        ports:
        - containerPort: 8081