apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: cm9vdA==
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo
  namespace: qq3
---
apiVersion: v1
data:
  ME_CONFIG_BASICAUTH: "false"
  ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mongo-config
  namespace: qq3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: qq3
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: MONGO_INITDB_ROOT_PASSWORD
        ports:
        - containerPort: 27017
          name: mongo
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: ME_CONFIG_MONGODB_URL
        - name: ME_CONFIG_BASICAUTH
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: ME_CONFIG_BASICAUTH
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: MONGO_INITDB_ROOT_USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: MONGO_INITDB_ROOT_PASSWORD
        ports:
        - containerPort: 8081
          name: mongo-express
