apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: aGFmemFu
  ME_CONFIG_MONGODB_ADMINPASSWORD: aGFmemFu
  MONGO_INITDB_ROOT_USERNAME: aGFmemFu
  MONGO_INITDB_ROOT_PASSWORD: aGFmemFu