apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4K
  MONGO_INITDB_ROOT_PASSWORD: aGVsbG8K
  ME_CONFIG_MONGODB_ADMINUSERNAME: YWRtaW4K
  ME_CONFIG_MONGODB_ADMINPASSWORD: aGVsbG8K